version: 0.2

phases:
  pre_build:
    commands:
      - echo Retrieving Docker Hub credentials...
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query 'SecretString' --output text | jq -r '.username')
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query 'SecretString' --output text | jq -r '.password')
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 600897147573.dkr.ecr.us-west-2.amazonaws.com
      - echo "Current directory:"
      - echo "Listing files in current directory:"
      - ls -la
      - echo "Navigating to source directory..."
      - cd $CODEBUILD_SRC_DIR
      - echo "Listing files in source directory:"
      - ls -la
      - echo Archiving the code source...
      - zip -r source-code.zip

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest 600897147573.dkr.ecr.us-west-2.amazonaws.com/my-app:latest
      - echo Uploading the code to S3 bucket...
      - aws s3 cp source-code.zip s3://source-code-bucket-us-west-2/

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 600897147573.dkr.ecr.us-west-2.amazonaws.com/my-app:latest
      - echo Generating imagedefinitions.json...
      - echo '[{"name":"my-app","imageUri":"600897147573.dkr.ecr.us-west-2.amazonaws.com/my-app:latest"}]' > imagedefinitions.json
      - echo Build completed on `date`

artifacts:
  files:
    - imagedefinitions.json
